name: Build and Test React Application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Set permissions for scripts
        run: chmod +x node_modules/.bin/react-scripts
      - name: Run tests
        env:
          REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_MY_SPOTIFY_CLIENT_ID }}
          REACT_APP_OPENAI_API_KEY: ${{ secrets.REACT_APP_MY_OPENAI_API_KEY }}
        run: npm test -- --json > test_output.json
      - name: Upload test output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test_output.json
